export const ACTIONS = {
  VIEW: 'VIEW',
  CREATE: 'CREATE',
  EDIT: 'EDIT',
  APPROVE: 'APPROVE',
  DELETE: 'DELETE',
  VOID: 'VOID',
  CONFIGURE: 'CONFIGURE',
} as const;

export type Action = (typeof ACTIONS)[keyof typeof ACTIONS];

// Resource keys per module
export const RESOURCES = {
  // Core
  USERS: 'USERS',
  ROLES: 'ROLES',
  CONFIG: 'CONFIG',
  SEQUENCES: 'SEQUENCES',
  // Procurement
  SUPPLIERS: 'SUPPLIERS',
  MRL: 'MRL',
  PRL: 'PRL',
  ENQUIRY: 'ENQUIRY',
  QUOTATION: 'QUOTATION',
  PO: 'PO',
  SUPPLIER_RETURN: 'SUPPLIER_RETURN',
  // Inventory
  ITEMS: 'ITEMS',
  WAREHOUSES: 'WAREHOUSES',
  GRN: 'GRN',
  STOCK_ISSUE: 'STOCK_ISSUE',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  PHYSICAL_COUNT: 'PHYSICAL_COUNT',
  // Finance
  GL_ACCOUNTS: 'GL_ACCOUNTS',
  COST_CENTERS: 'COST_CENTERS',
  JOURNAL: 'JOURNAL',
  AP_INVOICE: 'AP_INVOICE',
  AP_PAYMENT: 'AP_PAYMENT',
  AR_INVOICE: 'AR_INVOICE',
  AR_RECEIPT: 'AR_RECEIPT',
  BUDGET: 'BUDGET',
  // Sales
  CUSTOMERS: 'CUSTOMERS',
  PRICE_LIST: 'PRICE_LIST',
  SALES_ENQUIRY: 'SALES_ENQUIRY',
  SALES_QUOTATION: 'SALES_QUOTATION',
  SALES_ORDER: 'SALES_ORDER',
  DELIVERY_NOTE: 'DELIVERY_NOTE',
  SALES_INVOICE: 'SALES_INVOICE',
  SALES_RETURN: 'SALES_RETURN',
  CREDIT_NOTE: 'CREDIT_NOTE',
  SALES_CONTRACT: 'SALES_CONTRACT',
  PROGRESS_BILL: 'PROGRESS_BILL',
  CREDIT_CONTROL: 'CREDIT_CONTROL',
} as const;

export type Resource = (typeof RESOURCES)[keyof typeof RESOURCES];

// Built-in system roles
export const SYSTEM_ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  PROCUREMENT_MANAGER: 'PROCUREMENT_MANAGER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_OFFICER: 'SALES_OFFICER',
  SALES_COORDINATOR: 'SALES_COORDINATOR',
  CREDIT_CONTROLLER: 'CREDIT_CONTROLLER',
  BILLING_OFFICER: 'BILLING_OFFICER',
} as const;

export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];
